services:
  mailing:
    image: axllent/mailpit:latest
    restart: unless-stopped
    profiles: ["mailcatcher"]
    volumes:
      - maildir_volume:/data
    environment:
      MP_DATA_FILE: /data/mailpit.db
      MP_UI_AUTH: ${MAIL_USERNAME}:${MAIL_PASSWORD}
      MP_SMTP_AUTH: ${MAIL_USERNAME}:${MAIL_PASSWORD}
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      TZ: Europe/Paris
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailing.rule=Host(`mailing.${DOMAIN}`)
      - traefik.http.services.mailing.loadbalancer.server.port=8025

volumes:
  maildir_volume:
