services:
  orchestrator:
    image: traefik:v2.9
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
