import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useQuery } from '@tanstack/react-query';
import fetchOneByDate from '../utils/wordsPool/fetchOneByDate'
import {useEffect} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const day = '2024-01-17'

    const { isLoading, data } = useQuery({
        queryKey: ['wordsPoolOfDay', day],
        queryFn: () => fetchOneByDate(day),
    });

    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className + ' bg-slate-50 min-h-screen overflow-auto'}>
          <div className="container mx-auto">
              <h1 className="mx-auto text-center text-5xl font-bold mt-5">Les Mots</h1>
          </div>
          {JSON.stringify(data, null, 2)}
      </main>
    </>
  )
}
