services:
  backend:
    build:
      context: ../backend
      target: backend-local
      args:
        DOCKER_UID: ${DOCKER_UID-1000}
        DOCKER_GID: ${DOCKER_GID-1000}
    volumes:
      - ../backend:/var/www/html/:delegated
    environment:
      # LARAVEL SPECIFICS
      APP_NAME: ${APP_NAME}
      APP_ENV: ${COMPOSE_PROFILES}
      APP_DEBUG: ${DEBUG}
      APP_URL: ${HTTP_PROTOCOL}://${DOMAIN}
      HTTP_PROTOCOL: ${HTTP_PROTOCOL}
      SANCTUM_STATEFUL_DOMAINS: ${SANCTUM_STATEFUL_DOMAINS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SESSION_DOMAIN: .${DOMAIN}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  backend_webserver:
    build:
      context: ../backend
      target: webserver-local
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_webserver.rule=Host(`backend.${DOMAIN}`)
    volumes:
      - ../backend:/var/www/html/:delegated

  backend_cron:
    extends: backend
    build:
      context: ../backend
      target: backend-cron-local
