services:
  backend:
    build:
      context: ../backend
      target: backend-local
      args:
        DOCKER_UID: ${DOCKER_UID-1000}
        DOCKER_GID: ${DOCKER_GID-1000}
    volumes:
      - ../backend:/var/www/html/:delegated
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  backend_webserver:
    build:
      context: ../backend
      target: webserver-local
    volumes:
      - ../backend:/var/www/html/:delegated

  backend_cron:
    extends: backend
    build:
      context: ../backend
      target: backend-cron-local
