services:
  lesmots_backend:
    build:
      context: ../backend
      target: backend-local
      args:
        DOCKER_UID: ${DOCKER_UID-1000}
        DOCKER_GID: ${DOCKER_GID-1000}
    volumes:
      - ../backend:/var/www/html/:delegated
    environment:
      # LARAVEL SPECIFICS
      APP_URL: ${HTTP_PROTOCOL}://${DOMAIN}
      SESSION_DOMAIN: .${DOMAIN}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  lesmots_backend_webserver:
    build:
      context: ../backend
      target: webserver-local
    labels:
      - traefik.http.routers.lesmots_backend_webserver.rule=Host(`backend.${DOMAIN}`)
    volumes:
      - ../backend:/var/www/html/:delegated

  lesmots_backend_cron:
    extends: lesmots_backend
    build:
      context: ../backend
      target: backend-cron-local
