services:
  frontend:
    build:
      context: ../frontend
      target: frontend-local
    volumes:
      - ../frontend:/app:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
