services:
  orchestrator:
    image: traefik:v2.10
    ports:
      - 80:80
      - 8080:8080
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,delegated
