services:
  platform:
    environment:
      ENV: ${ENV}
      HTTP_PROTOCOL: ${HTTP_PROTOCOL}
      DOMAIN: ${DOMAIN}
      APP_NAME: ${APP_NAME}
      NEXT_PUBLIC_API_BASE_URL: ${HTTP_PROTOCOL}://api.${DOMAIN}
    build:
      context: ../platform
      target: platform-local
    volumes:
      - ../platform:/app:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.platform.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.platform.tls=true

