services:
  backend:
    image: ${REGISTRY_ADDRESS}lesmots-backend:main
    restart: always
    environment:
      TEMPLATE_PHP_INI: production
      SESSION_SECURE_COOKIE: 1
    volumes:
      - lesmots_backend_storage:/var/www/html/storage

  backend_webserver:
    image: ${REGISTRY_ADDRESS}lesmots-backend_webserver:main
    restart: always
    volumes:
      - lesmots_backend_webserver_logs:/static-logs
    labels:
      - traefik.http.routers.backend_webserver.entrypoints=websecure
      - traefik.http.routers.backend_webserver.tls.certresolver=httpsresolver

  backend_cron:
    extends: backend
    image: ${REGISTRY_ADDRESS}lesmots-backend_cron:main
    restart: always

volumes:
  lesmots_backend_storage:
  lesmots_backend_webserver_logs:
