services:
  platform_webserver:
    image: ${REGISTRY_ADDRESS}${PROJECT_NAME}-platform:main
    environment:
      ENV: ${ENV}
      HTTP_PROTOCOL: ${HTTP_PROTOCOL}
      DOMAIN: ${DOMAIN}
      APP_NAME: ${APP_NAME}
      NEXT_PUBLIC_API_BASE_URL: ${HTTP_PROTOCOL}://api.${DOMAIN}
    restart: always
    volumes:
      - platform_webserver_logs:/static-logs
    labels:
      - traefik.enable=true
      - traefik.http.routers.platform_webserver.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.platform_webserver.entrypoints=websecure
      - traefik.http.routers.platform_webserver.tls.certresolver=httpsresolver

volumes:
  platform_webserver_logs:
