#!/bin/sh
set -e

mkdir -p \
  /var/www/html/storage/app/public \
  /var/www/html/storage/framework/cache/data \
  /var/www/html/storage/framework/sessions \
  /var/www/html/storage/framework/testing \
  /var/www/html/storage/framework/views \
  /var/www/html/storage/logs

chown -R www-data: /var/www/html/storage

nginx -g 'daemon off;' &
/usr/local/bin/docker-php-entrypoint "$@" &

wait -n
exit $?
