name: Analyse API
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Setup API
        working-directory: api
        run: cp .env.example .env
      - name: Install Composer Dependencies
        working-directory: api
        run: composer install --prefer-dist
      - name: Run Analysis
        working-directory: api
        run: composer phpstan

